// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "陈序缘",
            "url": "https://github.com/go75?tab=repositories"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/group/head/{filename}": {
            "get": {
                "description": "获取群聊头像",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "群聊模块"
                ],
                "summary": "群聊头像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群聊名.png",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/group/regist": {
            "post": {
                "description": "群聊注册服务",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "群聊模块"
                ],
                "summary": "群聊注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "群聊名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "群聊介绍",
                        "name": "introduce",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "群聊头像",
                        "name": "head",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/head/{filename}": {
            "get": {
                "description": "获取用户头像",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户头像",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名.png",
                        "name": "filename",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "用户登录服务",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户密码",
                        "name": "pwd",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/regist": {
            "post": {
                "description": "用户注册服务",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户模块"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "用户密码",
                        "name": "pwd",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "确认密码",
                        "name": "check",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "用户头像",
                        "name": "head",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0 版本",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "im系统http网关接口",
	Description:      "http网关功能: 登录, 注册, 头像",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
